// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikfaefxtpcfqwziwjnka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZmFlZnh0cGNmcXd6aXdqbmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzg3NjEsImV4cCI6MjA2Nzg1NDc2MX0.2ciHewXxHtA9gY70P2tB_eSGVtHilK8x-tYnPvTkuh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});